version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 30
  assignees:
  - Chesire
  labels:
  - "dependencies"

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 30
  assignees:
  - Chesire
  labels:
  - "dependencies"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 30
  assignees:
  - Chesire
  labels:
  - "dependencies"
