name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shadowJar
        run: ./gradlew shadowJar

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run test
        run: ./gradlew test
      - name: run koverReport
        run: ./gradlew koverReport
      - uses: codecov/codecov-action@v3.0.0

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck

  analyze:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: run detektCheck
        run: ./gradlew detektCheck  
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
