name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run shadowJar
        run: ./gradlew shadowJar
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run test
        run: ./gradlew test
        
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck
        
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run detektCheck
        run: ./gradlew detektCheck
      - name: Danger
        uses: danger/kotlin@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
